Repository Medology/FlexibleMink, pull requests merged in 2018-12, with the labels that each got.

#198 Creating Method to Assert Element is not Covered by Another
  features/FlexibleContext/assertElementIsNotCovered.feature
  src/Behat/FlexibleMink/Context/FlexibleContext.php
  web/covering-elements.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#199 Creating Method to Assert Element is not Covered by Another
  features/FlexibleContext/assertElementIsNotCovered.feature
  src/Medology/Behat/Mink/FlexibleContext.php
  web/covering-elements.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#208 Move selectOption from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#209 Modifying assertElementIsNotCovered method to account for elements in the tested element
  src/Behat/FlexibleMink/Context/FlexibleContext.php
  web/covering-elements.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#210 Modifying assertElementIsNotCovered method to account for elements in the tested element 2
  src/Medology/Behat/Mink/FlexibleContext.php
  web/covering-elements.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#211 2.0 refactor
  behat.yml
  features/FlexibleContext/assertElementIsFullyDisplayed.feature
  src/Medology/Behat/Mink/FlexibleContext.php
  src/Medology/Behat/Mink/Models/Geometry/Rectangle.php
  src/Medology/Behat/Mink/QualityAssurance.php
  web/ScrollableDivs.html
Labels: ✓ Back-End Review, ✓ Front-End Review

#217 2.0 extended visibility Methods
  composer.lock
  features/FlexibleContext/assertElementIsDisplayed.feature
  features/FlexibleContext/assertElementIsFullyDisplayed.feature
  features/FlexibleContext/assertElementIsInDocument.feature
  src/Medology/Behat/Mink/FlexibleContext.php
  src/Medology/Behat/Mink/Models/Geometry/Rectangle.php
  src/Medology/Behat/Mink/QualityAssurance.php
  web/ScrollableDivs.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review
