Repository Medology/FlexibleMink, pull requests merged in 2018-11, with the labels that each got.

#171 Declare requirement for zip extension
  composer.json
  composer.lock
Labels: ✓ Testing Review

#175 Move assertElementOnPage from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#178 Move assertElementInsideElement from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#172 Fix getThingProperty does not build key
  src/Medology/Behat/StoreContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#177 Move assertElementInsideElement from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#173 Fix fillField doesn't inject stored values into value arg
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#170 Exception cleanup
  src/Medology/Behat/Mink/FlexibleContext.php
  src/Medology/Behat/StoreContext.php
  src/Medology/Spinner.php
  src/Medology/SpinnerTimeoutException.php
Labels: ✓ Back-End Review, ✓ Testing Review

#179 Move assertFieldContains from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#180 Move assertFieldContains from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#176 Move assertElementOnPage from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#182 Move pressButton from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#181 Move assertPageAddress from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#183 Move pressButton from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#189 Move assertJavascriptVariables from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/JavaScriptContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#187 Move comparElementsByCoords from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#194 Move waitForPageLoad from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
  src/Medology/Spinner.php
Labels: ✓ Back-End Review, ✓ Testing Review

#192 Move elementHasAttributeValues from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#195 Move waitForPageLoad from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Testing Review, ✘ Back-End Review

#185 Move assertPageAddress from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#193 Move elementHasAttributeValues from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#196 Move assertButtonExists from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#197 Move assertButtonExists from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#186 Assert that an element is visible to the user.
  composer.json
  composer.lock
  features/FlexibleContext/assertElementIsFullyDisplayed.feature
  src/Behat/FlexibleMink/Context/FlexibleContext.php
  src/Behat/FlexibleMink/Models/Geometry/Rectangle.php
  web/ScrollableDivs.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#191 Assert that an element is visible to the user.
  composer.json
  composer.lock
  features/FlexibleContext/assertElementIsFullyDisplayed.feature
  src/Medology/Behat/Mink/FlexibleContext.php
  src/Medology/Behat/Mink/Models/Geometry/Rectangle.php
  web/ScrollableDivs.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#202 Move assertJavascriptVariables from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/JavaScriptContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#203 Move all cookies (delete, get) from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#204 Move all cookies (delete, get) from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#205 Move attachFileToField from STDcheck to FlexibleMink
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#206 Move attachFileToField from STDcheck to FlexibleMink
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review
