Repository Medology/FlexibleMink, pull requests merged in 2018-03, with the labels that each got.

#135 Fixing issue with asserting field exists
  features/FlexibleContext/assertFieldExists.feature
  src/Behat/FlexibleMink/Context/FlexibleContext.php
  src/Behat/FlexibleMink/PseudoInterface/FlexibleContextInterface.php
  web/assert-field-exists.html
Labels: ✓ Back-End Review, ✓ Testing Review

#137 2.0
  features/FlexibleContext/assertFieldExists.feature
  src/Medology/Behat/Mink/FlexibleContext.php
  web/assert-field-exists.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#138 The `getInputsByLabel` method that was modified before, was attemptin…
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review

#139 small change to `getInputsByLabel`
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#141 Make TableContext::getTableFromName public
  src/Medology/Behat/Mink/TableContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#140 Make TableContext::getTableFromName public
  src/Behat/FlexibleMink/Context/TableContext.php
  src/Behat/FlexibleMink/PseudoInterface/TableContextInterface.php
Labels: ✓ Back-End Review, ✓ Testing Review
