Repository Medology/FlexibleMink, pull requests merged in 2019-01, with the labels that each got.

#219 [1.0] Fix viewport visibility checks not working on scrolled pages
  features/FlexibleContext/assertElementIsDisplayed.feature
  src/Behat/FlexibleMink/Context/FlexibleContext.php
  web/big-page.html
Labels: ✓ Back-End Review, ✓ Front-End Review, ✓ Testing Review

#221 Fix assertFieldContains() calls undefined method
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#222 Fix assertJavascriptVariables calls injectStoredValues on wrong object
  src/Medology/Behat/Mink/JavaScriptContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#223 Eliminate SpinnerTimeoutException by using do/while
  src/Medology/Behat/Mink/FlexibleContext.php
  src/Medology/Behat/Mink/QualityAssurance.php
  src/Medology/Spinner.php
  src/Medology/SpinnerTimeoutException.php
Labels: ✓ Back-End Review, ✓ Testing Review

#174 Add AsyncMink class
  src/Medology/Behat/Mink/AsyncMink.php
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#224 Asserting query params in the page url
  features/FlexibleContext/assertPageAddress.feature
  src/Behat/FlexibleMink/Context/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#225 Asserting query params in the page url
  features/FlexibleContext/assertPageAddress.feature
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#227 Allow registration of Store initialization lambdas
  src/Medology/Behat/StoreContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#226 selectOption supports context
  src/Medology/Behat/Mink/FlexibleContext.php
Labels: ✓ Back-End Review, ✓ Testing Review

#229 referToStoredAs() now supports Given
  src/Medology/Behat/StoreContext.php
Labels: ✓ Back-End Review

#230 referToStoredAs() now supports Given
  src/Behat/FlexibleMink/Context/StoreContext.php
Labels: ✓ Back-End Review, ✓ Testing Review
